const { chromium } = require("playwright")
const assert = require("node:assert/strict")

;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    const errors = []
    page.on("pageerror", error => errors.push(error.message))
    const base = process.env.DEMO_BASE_URL || "http://localhost:5173"
    const send = async text => {
      const input = page.getByRole("textbox", { name: "Message the assistant" })
      assert.equal(await input.count(), 1)
      await input.fill(text)
      await input.press("Enter")
    }
    const idle = () => page.getByRole("button", { name: "Send message", exact: true }).waitFor({ timeout: 30000 })
    await page.goto(base)
    await page.getByRole("button", { name: "AI Agent", exact: true }).click()
    await page.getByRole("menuitem", { name: "Unified Demo", exact: true }).click()
    assert.equal(new URL(page.url()).pathname, "/unified-demo")
    await send("Help me with Amar")
    await page.getByText("Include “extension” to manage an extension request, or “inspection” to plan inspections.", { exact: true }).waitFor()
    assert.equal(await page.locator('[data-unified-flow="extension"]').count(), 0)
    await send("Please arrange an EXTENSION for Amar, then an inspection")
    const extension = page.locator('[data-unified-flow="extension"]')
    await extension.locator('[data-slot="selectable-reservation-card"]').first().waitFor({ timeout: 20000 })
    await idle()
    assert.equal(await page.locator('[data-unified-flow="inspection"]').count(), 0)
    assert.equal(await extension.locator('[data-slot="selectable-reservation-card"]').count(), 3)
    await extension.locator('[data-slot="selectable-reservation-card"]').first().click()
    await extension.getByRole("button", { name: "Select new check-out date" }).click()
    await page.getByRole("button", { name: /Saturday, November 16th, 2024/ }).click()
    await page.getByRole("button", { name: "Submit", exact: true }).click()
    await extension.getByRole("button", { name: "Create Extension", exact: true }).waitFor({ timeout: 10000 })
    await idle()
    await extension.getByRole("button", { name: "Create Extension", exact: true }).click()
    await page.getByRole("button", { name: "Send Payment Link", exact: true }).click()
    await page.getByRole("button", { name: "Close", exact: true }).last().waitFor({ timeout: 10000 })
    await page.getByRole("button", { name: "Close", exact: true }).last().click()
    await extension.getByText("Payment Email Sent", { exact: true }).waitFor()
    await send("Please start an InSpEcTiOn for Lana Tower before the extension")
    const inspection = page.locator('[data-unified-flow="inspection"]').first()
    await inspection.locator('[data-phase="planning"][data-mode="ready"]').waitFor({ timeout: 20000 })
    await idle()
    await page.getByRole("heading", { name: "Inspection schedule", exact: true }).waitFor()
    assert.equal(await extension.getByText("Payment Email Sent", { exact: true }).count(), 1)
    await inspection.getByRole("button", { name: "Use 5:45 PM", exact: true }).click()
    await inspection.locator('[data-phase="review"][data-mode="ready"]').waitFor({ timeout: 30000 })
    await idle()
    await inspection.getByRole("button", { name: "Confirm & notify residents", exact: true }).click()
    await inspection.locator('[data-phase="execution"][data-mode="ready"]').waitFor({ timeout: 20000 })
    await idle()
    assert.equal(await inspection.getByText("Lana Tower · Inspection plan confirmed", { exact: true }).count(), 2)
    await page.getByRole("button", { name: "Review full schedule", exact: true }).click()
    await page.getByRole("heading", { name: "Full Lana Tower schedule · 116 apartments", exact: true }).waitFor()
    await send("Another extension please")
    await idle()
    assert.equal(await page.getByRole("heading", { name: "Inspection schedule", exact: true }).count(), 0)
    assert.equal(await page.locator('[data-unified-flow="extension"]').count(), 2)
    assert.equal(await inspection.locator('[data-phase="execution"][data-mode="ready"]').count(), 1)
    assert.equal(await page.getByRole("textbox", { name: "Message the assistant" }).count(), 1)
    assert.equal(await page.getByText(/Tower C/).count(), 0)
    await page.setViewportSize({ width: 390, height: 844 })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
    await inspection.getByText("Lana Tower · Inspection plan confirmed", { exact: true }).first().click()
    await page.getByRole("heading", { name: "Inspection schedule", exact: true }).waitFor()
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
    await page.waitForTimeout(800)
    const geometry = await page.locator('[data-unified-chat-scroll]').evaluate(element => ({ width: element.clientWidth, scrollWidth: element.scrollWidth, left: element.scrollLeft }))
    assert.equal(geometry.left, 0)
    assert.equal(geometry.scrollWidth, geometry.width)
    await page.screenshot({ path: "/tmp/unified-demo-mobile.png", fullPage: true })
    assert.deepEqual(errors, [])
    console.log("Unified Demo browser checks passed: routing, both complete flows, history, one composer, panel switching, and mobile width.")
  } finally {
    await browser.close()
  }
})().catch(error => { console.error(error); process.exitCode = 1 })
